version: "3.8"

services:
  minecraft:
    build: .
    container_name: dockercraft
    ports:
      - "25565:25565"
    volumes:
      - ./server.jar:/minecraft/server.jar
      - ./world:/minecraft/world
      - ./backup:/minecraft/backup
      - ./log:/minecraft/log
      - ./fifo:/minecraft/fifo
    environment:
      - SERVER_PATH=/minecraft
      - FIFO_PATH=/minecraft/fifo
      - BACKUP_DIR=backup
      - LOG_DIR=log
      - MEMORY_MIN=2G
      - MEMORY_MAX=4G
    restart: unless-stopped
    stdin_open: true
    tty: true
