version: "3.8"

services:
  minecraft:
    build: .
    container_name: dockercraft
    ports:
      - "25565:25565"
    volumes:
      - ./server.jar:/minecraft/server.jar
      - ./backups:/minecraft/backups
      - ./logs:/minecraft/logs
      - ./fifo:/minecraft/fifo
      - ./server:/minecraft
    environment:
      - SERVER_PATH=/minecraft
      - FIFO_PATH=fifo
      - BACKUP_DIR=backups
      - LOG_DIR=logs
      - MEMORY_MIN=2G
      - MEMORY_MAX=4G
      - MAX_LOGS=10
      - MAX_BACKUPS=10
    restart: unless-stopped
    stdin_open: true
    tty: true
